version: "3.8"

services:
  ridemate-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ridemate-backend:latest
    container_name: ridemate-backend
    ports:
      - "8090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ridemate-db:3306/ridemate
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: FontysPass12#
      JAVA_OPTS: "-Xms256m -Xmx512m"
    depends_on:
      - ridemate-db
    networks:
      - ridemate-network
    restart: unless-stopped

  ridemate-db:
    image: mysql:latest
    container_name: ridemate-db
    environment:
      MYSQL_DATABASE: ridemate
      MYSQL_ROOT_PASSWORD: FontysPass12#
    ports:
      - "3307:3306"  # Changed external port to 3307
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ridemate-network
    restart: unless-stopped

  ridemate-frontend:
    build:
      context: ../RideMate/
      dockerfile: Dockerfile
    image: ridemate-frontend:latest
    container_name: ridemate-frontend
    ports:
      - "5174:80"
    depends_on:
      - ridemate-backend
    networks:
      - ridemate-network
    restart: unless-stopped

networks:
  ridemate-network:
    driver: bridge

volumes:
  db_data:
